name: Update MSW Service Worker

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - pnpm-lock.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  UpdateMSW:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'renovate[bot]'
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Setup Project
        uses: ./.github/actions/setup

      - name: Update and commit mockServiceWorker.js
        run: |
          pnpm msw init public --save
          git add public/mockServiceWorker.js
          if ! git diff --staged --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: update mockServiceWorker.js"
            git push
          fi
